<?php

declare(strict_types=1);

namespace Modules\Returns\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Returns\Models\ReturnDefinition;

class ReturnDefinitionsSeeder extends Seeder
{
    public function run(): void
    {
        $tenantId = 1;

        $definitions = [
            [
                'code' => 'CBN-AML-MONTHLY',
                'title' => 'Monthly AML Compliance Status Report to Board',
                'description' => 'Monthly report on the status of AML/CFT/CPF compliance submitted to the Board of Directors.',
                'acts' => 'Money Laundering (Prevention and Prohibition) Act 2022',
                'legal_basis' => 's. 9(4)',
                'regulator' => 'cbn',
                'submission_channel' => 'portal',
                'file_format' => 'pdf',
                'frequency' => 'monthly',
                'responsible_unit' => 'Compliance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'CBN-AML-ANNUAL',
                'title' => 'Annual Report on AML/CFT/CPF Compliance to CBN',
                'description' => 'Annual comprehensive AML/CFT/CPF compliance report submitted to the Central Bank of Nigeria.',
                'acts' => 'Money Laundering (Prevention and Prohibition) Act 2022; Terrorism (Prevention and Prohibition) Act 2022',
                'legal_basis' => 's. 9(4), s. 33',
                'regulator' => 'cbn',
                'submission_channel' => 'portal',
                'file_format' => 'pdf',
                'frequency' => 'annual',
                'responsible_unit' => 'Compliance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'NFIU-STR',
                'title' => 'Suspicious Transaction Reports (STR)',
                'description' => 'Reports of suspicious transactions filed with the Nigerian Financial Intelligence Unit via goAML.',
                'acts' => 'Money Laundering (Prevention and Prohibition) Act 2022',
                'legal_basis' => 's. 6(1)',
                'regulator' => 'nfiu',
                'submission_channel' => 'goaml_xml',
                'file_format' => 'xml',
                'frequency' => 'event_driven',
                'responsible_unit' => 'AML/CFT Unit',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => false,
                'active' => true,
            ],
            [
                'code' => 'NFIU-CTR',
                'title' => 'Currency Transaction Reports (CTR)',
                'description' => 'Daily reports of cash transactions above the prescribed threshold filed with NFIU.',
                'acts' => 'Money Laundering (Prevention and Prohibition) Act 2022',
                'legal_basis' => 's. 10',
                'regulator' => 'nfiu',
                'submission_channel' => 'goaml_xml',
                'file_format' => 'xml',
                'frequency' => 'daily',
                'responsible_unit' => 'AML/CFT Unit',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'compliance_officer', 'approver_role' => 'compliance_officer'],
                'evidence_required' => false,
                'active' => true,
            ],
            [
                'code' => 'NFIU-CDR',
                'title' => 'Currency Declaration Reports (CDR)',
                'description' => 'Event-driven reports of cross-border currency declarations filed with NFIU.',
                'acts' => 'Money Laundering (Prevention and Prohibition) Act 2022',
                'legal_basis' => 's. 11',
                'regulator' => 'nfiu',
                'submission_channel' => 'goaml_xml',
                'file_format' => 'xml',
                'frequency' => 'event_driven',
                'responsible_unit' => 'AML/CFT Unit',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'compliance_officer', 'approver_role' => 'compliance_officer'],
                'evidence_required' => false,
                'active' => true,
            ],
            [
                'code' => 'NDPC-BREACH',
                'title' => 'Data Breach Notification under NDPA',
                'description' => 'Mandatory notification to the Nigeria Data Protection Commission within 72 hours of discovering a personal data breach.',
                'acts' => 'Nigeria Data Protection Act 2023',
                'legal_basis' => 's. 40',
                'regulator' => 'ndpc',
                'submission_channel' => 'portal',
                'file_format' => 'pdf',
                'frequency' => 'event_driven',
                'responsible_unit' => 'Data Privacy Office',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'CBN-CYBER-INCIDENT',
                'title' => 'Cyber Incident Reports to CBN',
                'description' => 'Reports of significant cyber incidents submitted to CBN via email within prescribed SLA (4h internal, 24h external).',
                'acts' => 'CBN Risk-Based Cybersecurity Framework 2022',
                'legal_basis' => 'Section 4.2',
                'regulator' => 'cbn',
                'submission_channel' => 'email',
                'file_format' => 'pdf',
                'frequency' => 'event_driven',
                'responsible_unit' => 'Information Security',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'CBN-EFASS-MONTHLY',
                'title' => 'Monthly Returns to CBN eFASS',
                'description' => 'Monthly financial returns submitted to the CBN Electronic Financial Analysis and Surveillance System.',
                'acts' => 'Banks and Other Financial Institutions Act (BOFIA) 2020',
                'legal_basis' => 's. 23',
                'regulator' => 'cbn',
                'submission_channel' => 'cbn_efass',
                'file_format' => 'xlsx',
                'frequency' => 'monthly',
                'responsible_unit' => 'Finance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'FIRS-VAT-MONTHLY',
                'title' => 'Monthly VAT Returns to FIRS',
                'description' => 'Monthly Value Added Tax returns filed with the Federal Inland Revenue Service via TaxPro Max.',
                'acts' => 'Value Added Tax Act (CAP V1) LFN 2004 as amended',
                'legal_basis' => 's. 15',
                'regulator' => 'firs',
                'submission_channel' => 'firs_tax_pro_max',
                'file_format' => 'xml',
                'frequency' => 'monthly',
                'responsible_unit' => 'Finance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'FIRS-PAYE-MONTHLY',
                'title' => 'Monthly PAYE Returns to FIRS',
                'description' => 'Monthly Pay-As-You-Earn returns filed with FIRS via TaxPro Max.',
                'acts' => 'Personal Income Tax Act (PITA) CAP P8 LFN 2004 as amended',
                'legal_basis' => 's. 81',
                'regulator' => 'firs',
                'submission_channel' => 'firs_tax_pro_max',
                'file_format' => 'xml',
                'frequency' => 'monthly',
                'responsible_unit' => 'Human Resources',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'FIRS-CIT-ANNUAL',
                'title' => 'Annual Company Income Tax Returns',
                'description' => 'Annual Company Income Tax returns filed with FIRS.',
                'acts' => 'Companies Income Tax Act (CITA) CAP C21 LFN 2004 as amended',
                'legal_basis' => 's. 55',
                'regulator' => 'firs',
                'submission_channel' => 'firs_tax_pro_max',
                'file_format' => 'xml',
                'frequency' => 'annual',
                'responsible_unit' => 'Finance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'SEC-AML-QUARTERLY',
                'title' => 'Quarterly Compliance Function Reports to SEC',
                'description' => 'Quarterly AML compliance function reports submitted to the Securities and Exchange Commission.',
                'acts' => 'Investments and Securities Act (ISA) 2007; SEC AML/CFT Rules 2019',
                'legal_basis' => 'Rule 4.1',
                'regulator' => 'sec',
                'submission_channel' => 'portal',
                'file_format' => 'pdf',
                'frequency' => 'quarterly',
                'responsible_unit' => 'Compliance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'PENCOM-RBS',
                'title' => 'Pension Scheme Compliance Returns to PenCom',
                'description' => 'Quarterly risk-based supervision compliance returns submitted to the National Pension Commission.',
                'acts' => 'Pension Reform Act 2014',
                'legal_basis' => 's. 89',
                'regulator' => 'pencom',
                'submission_channel' => 'portal',
                'file_format' => 'pdf',
                'frequency' => 'quarterly',
                'responsible_unit' => 'Human Resources',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'NDIC-DEPOSIT-INSURANCE',
                'title' => 'NDIC Deposit Insurance Returns',
                'description' => 'Monthly deposit insurance returns submitted to the Nigeria Deposit Insurance Corporation.',
                'acts' => 'Nigeria Deposit Insurance Corporation Act 2006',
                'legal_basis' => 's. 37',
                'regulator' => 'ndic',
                'submission_channel' => 'portal',
                'file_format' => 'xlsx',
                'frequency' => 'monthly',
                'responsible_unit' => 'Finance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
            [
                'code' => 'SCUML-QUARTERLY',
                'title' => 'Quarterly DNFBP Returns to SCUML',
                'description' => 'Quarterly AML/CFT compliance returns for Designated Non-Financial Businesses and Professions submitted to SCUML.',
                'acts' => 'Money Laundering (Prevention and Prohibition) Act 2022',
                'legal_basis' => 's. 5',
                'regulator' => 'scuml',
                'submission_channel' => 'portal',
                'file_format' => 'pdf',
                'frequency' => 'quarterly',
                'responsible_unit' => 'Compliance Department',
                'approval_matrix' => ['maker_role' => 'compliance_officer', 'checker_role' => 'risk_owner', 'approver_role' => 'compliance_officer'],
                'evidence_required' => true,
                'active' => true,
            ],
        ];

        foreach ($definitions as $data) {
            ReturnDefinition::firstOrCreate(
                ['tenant_id' => $tenantId, 'code' => $data['code']],
                array_merge($data, ['tenant_id' => $tenantId]),
            );
        }
    }
}
