<?php

declare(strict_types=1);

namespace Modules\Sanctkb\Database\Seeders;

use Illuminate\Database\Seeder;
use Modules\Library\Models\Regulator;
use Modules\Sanctkb\Models\Sanction;

class SanctionsSeeder extends Seeder
{
    public function run(): void
    {
        $regulators = Regulator::all()->keyBy('code');
        $data = $this->sanctionData();

        foreach ($data as $row) {
            $regulator = $regulators->get($row['regulator_code']);
            if (! $regulator) {
                continue;
            }

            Sanction::firstOrCreate(
                [
                    'reference' => $row['reference'],
                    'party_name' => $row['party_name'],
                ],
                [
                    'regulator_id' => $regulator->id,
                    'section' => $row['section'] ?? null,
                    'offence' => $row['offence'],
                    'party_type' => $row['party_type'] ?? 'institution',
                    'amount_naira' => $row['amount_naira'] ?? null,
                    'penalty_type' => $row['penalty_type'] ?? 'monetary',
                    'effective_date' => $row['effective_date'],
                    'source_url' => $row['source_url'] ?? null,
                ]
            );
        }
    }

    /** @return array<int, array<string, mixed>> */
    private function sanctionData(): array
    {
        return [
            // CBN sanctions
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/001',
                'section' => 'AML/CFT Regulation 15(2)',
                'party_name' => 'Bank A',
                'party_type' => 'institution',
                'offence' => 'Failure to conduct adequate customer due diligence on high-risk customers classified as Politically Exposed Persons; inadequate documentation of CDD measures applied.',
                'amount_naira' => 300_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-09-15',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/002',
                'section' => 'AML/CFT Regulation 22(1)',
                'party_name' => 'Bank B',
                'party_type' => 'institution',
                'offence' => 'Non-timely reporting of suspicious transactions; 14 STRs filed beyond the 24-hour deadline in Q3 2024.',
                'amount_naira' => 150_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-10-20',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/003',
                'section' => 'BOFIA 2020 S.31',
                'party_name' => 'Bank C',
                'party_type' => 'institution',
                'offence' => 'Breach of single obligor limit; aggregate exposure to a single related group exceeded permissible 20% threshold by ₦12.5bn.',
                'amount_naira' => 500_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-07-30',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/004',
                'section' => 'CBN Cybersecurity Framework S.5.1',
                'party_name' => 'Bank D',
                'party_type' => 'institution',
                'offence' => 'Failure to report a material cybersecurity incident to CBN within the required 1-hour notification window; incident detected on 12 August 2024 but reported on 14 August 2024.',
                'amount_naira' => 100_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-11-05',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/005',
                'section' => 'Consumer Protection Framework S.7',
                'party_name' => 'Bank E',
                'party_type' => 'institution',
                'offence' => 'Unauthorized deductions from customer accounts; failure to reverse erroneous charges within 24 hours; inadequate complaint resolution mechanism.',
                'amount_naira' => 75_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-08-18',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/006',
                'section' => 'AML/CFT Regulation 30(3)',
                'party_name' => 'Bank F',
                'party_type' => 'institution',
                'offence' => 'Inadequate screening of transactions against UN Security Council consolidated sanction lists; 6 transactions processed for designated entities.',
                'amount_naira' => 200_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-06-10',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/007',
                'section' => 'BOFIA 2020 S.25',
                'party_name' => 'Bank G',
                'party_type' => 'institution',
                'offence' => 'Late submission of audited financial statements to CBN; submitted 45 days beyond the 90-day statutory deadline.',
                'amount_naira' => 50_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-05-22',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/008',
                'section' => 'Open Banking Framework S.6',
                'party_name' => 'Bank H',
                'party_type' => 'institution',
                'offence' => 'Failure to implement customer consent withdrawal mechanisms as required by the CBN Open Banking Framework; customers unable to revoke data sharing consents.',
                'amount_naira' => 30_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-12-01',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/009',
                'section' => 'AML/CFT Regulation 8',
                'party_name' => 'Mr. John Doe (anonymised)',
                'party_type' => 'individual',
                'offence' => 'Compliance officer failed to implement adequate AML controls; deliberate suppression of 3 STR filings; personal fine imposed.',
                'amount_naira' => 10_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-10-01',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/010',
                'section' => 'BOFIA 2020 S.7(3)',
                'party_name' => 'Bank I',
                'party_type' => 'institution',
                'offence' => 'Operating a product without requisite CBN approval; launched embedded finance product without obtaining CBN no-objection letter.',
                'amount_naira' => 60_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-11-15',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/011',
                'section' => 'CBN Cybersecurity Framework S.3.1',
                'party_name' => 'Bank J',
                'party_type' => 'institution',
                'offence' => 'Board of Directors failed to approve Cybersecurity Policy within the prescribed annual cycle; 18-month gap in board approval.',
                'amount_naira' => 40_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-04-12',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/012',
                'section' => 'Consumer Protection Framework S.20',
                'party_name' => 'Bank K',
                'party_type' => 'institution',
                'offence' => 'Systematic failure to resolve customer complaints within 5 working days; 1,247 complaints exceeded resolution timeline in 2024.',
                'amount_naira' => 85_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2025-01-20',
            ],
            // NFIU sanctions
            [
                'regulator_code' => 'NFIU',
                'reference' => 'NFIU/ENF/2024/001',
                'section' => 'goAML Guidelines Art.4',
                'party_name' => 'Bank L',
                'party_type' => 'institution',
                'offence' => 'Failure to submit 23 Suspicious Transaction Reports via goAML within the 24-hour reporting window; manual paper submissions made instead.',
                'amount_naira' => 23_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-08-05',
            ],
            [
                'regulator_code' => 'NFIU',
                'reference' => 'NFIU/ENF/2024/002',
                'section' => 'CTR Requirements S.3',
                'party_name' => 'Bank M',
                'party_type' => 'institution',
                'offence' => 'System failure resulted in non-submission of Currency Transaction Reports for 45 days; 1,890 qualifying transactions not reported to NFIU.',
                'amount_naira' => 45_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-09-30',
            ],
            [
                'regulator_code' => 'NFIU',
                'reference' => 'NFIU/ENF/2024/003',
                'section' => 'MLPA 2022 S.6',
                'party_name' => 'Bank N',
                'party_type' => 'institution',
                'offence' => 'Tipping off a customer who was subject to a NFIU investigation; compliance officer disclosed investigation existence to account holder.',
                'amount_naira' => 50_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-07-18',
            ],
            // NDPC sanctions
            [
                'regulator_code' => 'NDPC',
                'reference' => 'NDPC/ENF/2024/001',
                'section' => 'NDPA 2023 S.40',
                'party_name' => 'Bank O',
                'party_type' => 'institution',
                'offence' => 'Failure to notify NDPC of personal data breach within 72 hours; breach involving 45,000 customer records reported 12 days after detection.',
                'amount_naira' => 90_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-11-28',
            ],
            [
                'regulator_code' => 'NDPC',
                'reference' => 'NDPC/ENF/2024/002',
                'section' => 'NDPA 2023 S.24',
                'party_name' => 'Bank P',
                'party_type' => 'institution',
                'offence' => 'Processing personal data without valid legal basis; bulk customer data transferred to a third-party service provider without data processing agreements.',
                'amount_naira' => 55_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-10-08',
            ],
            [
                'regulator_code' => 'NDPC',
                'reference' => 'NDPC/ENF/2024/003',
                'section' => 'NDPA 2023 S.26',
                'party_name' => 'Bank Q',
                'party_type' => 'institution',
                'offence' => 'Failure to commission annual data protection compliance audit for two consecutive years (2022 and 2023).',
                'amount_naira' => 20_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-06-14',
            ],
            // SEC sanctions
            [
                'regulator_code' => 'SEC',
                'reference' => 'SEC/ENF/2024/001',
                'section' => 'ISA 2007 S.111',
                'party_name' => 'Bank R (Capital Market Subsidiary)',
                'party_type' => 'institution',
                'offence' => 'Insider trading; a senior executive bought shares in an acquisition target 3 weeks before a public announcement using material non-public information.',
                'amount_naira' => 500_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-09-12',
            ],
            [
                'regulator_code' => 'SEC',
                'reference' => 'SEC/ENF/2024/002',
                'section' => 'SEC Rules Rule 19',
                'party_name' => 'Bank S',
                'party_type' => 'institution',
                'offence' => 'Late submission of quarterly capital market activity returns for Q1 and Q2 2024; filed 30 and 45 days beyond the deadline respectively.',
                'amount_naira' => 15_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-08-22',
            ],
            [
                'regulator_code' => 'SEC',
                'reference' => 'SEC/ENF/2024/003',
                'section' => 'SEC Rules Rule 45',
                'party_name' => 'Bank T',
                'party_type' => 'institution',
                'offence' => 'Operating a capital market operation without a current annual compliance certificate; certificate expired 8 months prior to detection.',
                'amount_naira' => 25_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-07-05',
            ],
            // FIRS sanctions
            [
                'regulator_code' => 'FIRS',
                'reference' => 'FIRS/ENF/2024/001',
                'section' => 'CITA S.27',
                'party_name' => 'Bank U',
                'party_type' => 'institution',
                'offence' => 'Late filing of Company Income Tax return; filed 4 months beyond the 6-month statutory deadline. Tax shortfall of ₦1.8bn with applicable surcharge and interest.',
                'amount_naira' => 180_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-10-25',
            ],
            [
                'regulator_code' => 'FIRS',
                'reference' => 'FIRS/ENF/2024/002',
                'section' => 'VAT Act S.15',
                'party_name' => 'Bank V',
                'party_type' => 'institution',
                'offence' => 'Failure to charge and remit VAT on fee-based services for 6 months; accumulated VAT liability of ₦450m plus penalties and interest.',
                'amount_naira' => 67_500_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-08-12',
            ],
            [
                'regulator_code' => 'FIRS',
                'reference' => 'FIRS/ENF/2024/003',
                'section' => 'TP Regulations Reg.5',
                'party_name' => 'Bank W',
                'party_type' => 'institution',
                'offence' => 'Failure to maintain contemporaneous transfer pricing documentation for related-party transactions worth ₦12bn.',
                'amount_naira' => 120_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-11-08',
            ],
            // NDIC sanctions
            [
                'regulator_code' => 'NDIC',
                'reference' => 'NDIC/ENF/2024/001',
                'section' => 'NDIC Act S.18',
                'party_name' => 'Bank X',
                'party_type' => 'institution',
                'offence' => 'Late remittance of annual deposit insurance premium; premium for FY2023 remitted 45 days beyond the 31 March deadline.',
                'amount_naira' => 12_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-05-15',
            ],
            [
                'regulator_code' => 'NDIC',
                'reference' => 'NDIC/ENF/2024/002',
                'section' => 'NDIC Premium Guidelines Art.7',
                'party_name' => 'Bank Y',
                'party_type' => 'institution',
                'offence' => 'Understating insurable deposit base in the premium assessment return; resulted in underpayment of premium by ₦85m.',
                'amount_naira' => 8_500_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-09-01',
            ],
            // PenCom sanctions
            [
                'regulator_code' => 'PenCom',
                'reference' => 'PenCom/ENF/2024/001',
                'section' => 'PRA 2014 S.11',
                'party_name' => 'Bank Z',
                'party_type' => 'institution',
                'offence' => 'Non-remittance of employee and employer pension contributions for 4 months; affected 2,300 employees; back-payment of ₦1.2bn required.',
                'amount_naira' => 120_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-07-22',
            ],
            [
                'regulator_code' => 'PenCom',
                'reference' => 'PenCom/ENF/2024/002',
                'section' => 'PRA 2014 S.20',
                'party_name' => 'Bank AA',
                'party_type' => 'institution',
                'offence' => 'Failure to maintain group life insurance for employees; insurance lapsed for 9 months without renewal.',
                'amount_naira' => 5_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-10-18',
            ],
            // NAICOM sanctions
            [
                'regulator_code' => 'NAICOM',
                'reference' => 'NAICOM/ENF/2024/001',
                'section' => 'Bancassurance Guidelines S.12',
                'party_name' => 'Bank BB',
                'party_type' => 'institution',
                'offence' => 'Failure to submit quarterly bancassurance returns to NAICOM for Q1 and Q2 2024; returns filed 60 days after the deadline.',
                'amount_naira' => 7_500_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-08-28',
            ],
            [
                'regulator_code' => 'NAICOM',
                'reference' => 'NAICOM/ENF/2024/002',
                'section' => 'Insurance Act 2003 S.10',
                'party_name' => 'Bank CC (Insurance Subsidiary)',
                'party_type' => 'institution',
                'offence' => 'Solvency margin fell below the statutory minimum for two consecutive quarters; failure to implement remediation plan within prescribed timeframe.',
                'amount_naira' => null,
                'penalty_type' => 'license_action',
                'effective_date' => '2024-12-10',
            ],
            // Additional CBN sanctions
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/013',
                'section' => 'BVN Guidelines S.4',
                'party_name' => 'Bank DD',
                'party_type' => 'institution',
                'offence' => 'Failure to link 340,000 accounts to BVN within the prescribed timeline; failure to act on NIBSS watch-list alerts for 12 customers.',
                'amount_naira' => 25_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-06-30',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/014',
                'section' => 'Minimum Capital Circular S.2',
                'party_name' => 'Bank EE',
                'party_type' => 'institution',
                'offence' => 'Failure to submit capital raise plan within 30 days of the CBN minimum capital circular deadline.',
                'amount_naira' => 10_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-05-10',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/015',
                'section' => 'BOFIA 2020 S.7',
                'party_name' => 'Bank FF',
                'party_type' => 'institution',
                'offence' => 'Appointment of Chief Risk Officer without prior CBN approval; CRO served in acting capacity for 8 months without fit-and-proper clearance.',
                'amount_naira' => 20_000_000.00,
                'penalty_type' => 'reprimand',
                'effective_date' => '2024-07-01',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/016',
                'section' => 'Corporate Governance Guidelines S.7',
                'party_name' => 'Bank GG',
                'party_type' => 'institution',
                'offence' => 'Board Audit Committee failed to hold quarterly meetings; two consecutive quarters with no meeting records.',
                'amount_naira' => 15_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-09-05',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/017',
                'section' => 'AML/CFT Regulation 41',
                'party_name' => 'Bank HH',
                'party_type' => 'institution',
                'offence' => 'Correspondent banking relationships maintained with a respondent bank on FATF high-risk jurisdiction list without enhanced due diligence.',
                'amount_naira' => 250_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-11-22',
            ],
            [
                'regulator_code' => 'NFIU',
                'reference' => 'NFIU/ENF/2024/004',
                'section' => 'MLPA 2022 S.9',
                'party_name' => 'Bank II',
                'party_type' => 'institution',
                'offence' => 'Failure to register on the goAML portal for 6 months after the NFIU mandatory registration deadline.',
                'amount_naira' => 5_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-04-18',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/018',
                'section' => 'PSB Framework S.11',
                'party_name' => 'Bank JJ (PSB Subsidiary)',
                'party_type' => 'institution',
                'offence' => 'Failure to file annual PSB operational returns by the prescribed March deadline; filed 70 days late.',
                'amount_naira' => 8_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2025-01-08',
            ],
            [
                'regulator_code' => 'NDPC',
                'reference' => 'NDPC/ENF/2024/004',
                'section' => 'NDPA 2023 S.34',
                'party_name' => 'Bank KK',
                'party_type' => 'institution',
                'offence' => 'Failure to respond to data subject access requests within the 72-hour initial acknowledgement window; 87 DSARs exceeded the timeline in 2024.',
                'amount_naira' => 35_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2025-02-12',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/019',
                'section' => 'Fintech Licensing Guidelines S.3',
                'party_name' => 'Bank LL (Fintech Subsidiary)',
                'party_type' => 'institution',
                'offence' => 'Operating a payment switching service without the required CBN switching licence for 11 months.',
                'amount_naira' => 100_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-12-20',
            ],
            [
                'regulator_code' => 'CBN',
                'reference' => 'CBN/BSD/DIR/PUB/LAB/007/020',
                'section' => 'IMTS Guidelines S.7',
                'party_name' => 'Bank MM',
                'party_type' => 'institution',
                'offence' => 'Processing international money transfers through a non-approved IMTS operator; 5,400 transactions over 6 months.',
                'amount_naira' => 54_000_000.00,
                'penalty_type' => 'monetary',
                'effective_date' => '2024-08-01',
            ],
        ];
    }
}
